### ISSUE TITLE
Audit

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-quarkus#10]
JHipster Spring proposes an Audit configuration and UI which is pretty neat.

As for now, Quarkus does not have any alternative so let's be creative 😄

**Comment by danielpetisme** [comment]
https://twitter.com/vlad_mihalcea/status/1272166854891536386?s=19

**Comment by joewhite101** [comment]
@danielpetisme I think the audit UI were taken out for JH 7. Should we still do this do you think? Or is this still useful for the config side alone?

**Comment by pascalgrimaud** [comment]
I think this ticket should be closed
are you ok @danielpetisme ?

**Comment by avdev4j** [comment]
IMO we can close this one as we removed audits for the v7

**Comment by danielpetisme** [comment]
Since it's removed from the upstream jhipster project, it does not make sense anymore.

For the record, Quarkus has now a Envers extension to support auditability which was not the case when I created the issue. If someone wants to implement, the best option would be a dedicated jhipster module I guess.
