### ISSUE TITLE
Data migration for users management

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-quarkus#11]
JHipster Spring uses liquibase to init the database.

Quarkus has a flyway extension which could do the job too.

**Comment by amanganiello90** [comment]
I can to this.

**Comment by danielpetisme** [comment]
@amanganiello90 I'll take this one or at least a first version. I should propose something before the end of the week.

**Comment by danielpetisme** [comment]
I rename the issue to split the data migration between:
* the built-in user management 
* the user related entities.

The first one is done by #28
