### ISSUE TITLE
Support task questions

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/jhipster-quarkus#13]
Hi @danielpetisme ,
I would you like to contribute to this blueprint, I use already quarkus for my projects.
If you want, you can assigne me some issues. Thanks

**Comment by cchunduri** [comment]
HI @danielpetisme,

I'm interested to contribute to this project as part of my learning about quarks. Do assign some task to me so that i'll start working on them. Thank you.

**Comment by danielpetisme** [comment]
Sweet!! Do you have some specific point of interests?

**Comment by amanganiello90** [comment]
> 
> 
> Sweet!! Do you have some specific point of interests?

I have commented some issued that I could do. Besides there are some my PR

**Comment by danielpetisme** [comment]
@cchunduri do you have experience with JHipster blueprints? just to know which kind of issue I can assign you.

**Comment by cchunduri** [comment]
Hi @danielpetisme, I would like to work on pagination for now.

**Comment by danielpetisme** [comment]
Issue gardening
