### ISSUE TITLE
User Management API

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-quarkus#22]
**Is your feature request related to a problem? Please describe.**
Provide a Quarkus implementation of the User Management API.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by amanganiello90** [comment]
Hi @danielpetisme , Do you want to provide the user management adding api of [this jhipster template](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs) ? If you want, I can work on this feature.

**Comment by danielpetisme** [comment]
This is exactly what I want to do and I started already. I have couple of issues I'm dealing with RedHat.
If you want you can start the "Account" part (email registration etc) feel free but otherwise I'm working on it

**Comment by amanganiello90** [comment]
> 
> 
> This is exactly what I want to do and I started already. I have couple of issues I'm dealing with RedHat.
> If you want you can start the "Account" part (email registration etc) feel free but otherwise I'm working on it

ok, I will work on entity generation, thanks.

**Comment by pascalgrimaud** [comment]
@danielpetisme :
- don't forget to comment the ticket and mention me, so I'm sure you're the one who submitted the expense. By this way, I don't need to check the same mail. For this, it's ok, I checked and approuved the bounty
- then, is this ticket fixed ? As the other PR is merged but this one is not closed ?

**Comment by danielpetisme** [comment]
Hello @pascalgrimaud 
Sorry it's my first bounty, I do confirm the issue is closed by https://github.com/jhipster/jhipster-quarkus/pull/28

Thank you
