### ISSUE TITLE
Gradle integration

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-quarkus#25]
**Is your feature request related to a problem? Please describe.**
Gradle is an official option for JHipster, it must be implemented just as Maven is.

**Describe the solution you'd like**
Being able to build a generated application with Gradle.

**Describe alternatives you've considered**

**Additional context**
See #23

**Comment by mraible** [comment]
Can you please add bug bounty labels and amounts to this project and give me permission to assign them? I want to spend Okta's donations! 😀

**Comment by joewhite101** [comment]
Is this one resolved with the merged commits? Or is it something that needs more work?

**Comment by danielpetisme** [comment]
Fixed via #62
