### ISSUE TITLE
React variant of generated App UserManagement Broken

### ISSUE THREAD

**Issue by sirAlexanderT** [jhipster/jhipster-quarkus#59]
**Describe the bug**
Install as normal, but select react for the front end

**To Reproduce**
Trying to get to the User Management screen results in this

<img width="1668" alt="Screenshot 2020-05-25 at 21 07 07" src="https://user-images.githubusercontent.com/39586746/82840905-246f1c80-9ecc-11ea-8cd0-a07a986cad12.png">

**Comment by danielpetisme** [comment]
Hello @deepu105 do you have some hints to troubleshoot the above issue. I'm not familiar with React at all and since it's based on the default generation I'm wondering if there is no obvious "configurations" we could have missed.

**Comment by inngvar** [comment]
I use React, and with current version of generator UserManagement works fine

**Comment by deepu105** [comment]
Thats strange. You are not modifying the front end right. Also it could be that there is an issue but it only happens when certain conditions are met. I'll take a look when I have time. In the meantime may be compare the exact same config with a default app without blueprint

**Comment by joewhite101** [comment]
I think this has been overcome by events. Seems like this is working with the latest generator.

@sirAlexanderT Please try the latest and let us know. I'm closing now but we can reopen if you are still running into issues.
