### ISSUE TITLE
Upgrade to Quarkus latest release (1.7.0 as of this ticket)

### ISSUE THREAD

**Issue by joewhite101** [jhipster/jhipster-quarkus#66]
**Is your feature request related to a problem? Please describe.**
Blueprint should be on the latest

**Describe the solution you'd like**
Blueprint generates a 1.7 quarkus project

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/quarkusio/quarkus/releases

**Comment by joewhite101** [comment]
I'll work this one but can't assign it to myself. If it can be marked I'll own it.

**Comment by joewhite101** [comment]
Never mind. Already PR'd. Can we merge?
https://github.com/jhipster/jhipster-quarkus/pull/65

**Comment by danielpetisme** [comment]
Fixed
