### ISSUE TITLE
Upgrade to JHipster latest (6.10.1 as of this writing)

### ISSUE THREAD

**Issue by joewhite101** [jhipster/jhipster-quarkus#67]
**Is your feature request related to a problem? Please describe.**
Blueprint should run on JHipster latest

**Describe the solution you'd like**
We should be on the latest JHipster for Quarkus

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/jhipster/generator-jhipster/releases

**Comment by joewhite101** [comment]
I'll take this one but can't assign to myself. Please assign to me.

**Comment by joewhite101** [comment]
Never mind on assignment. Already PR'd.
https://github.com/jhipster/jhipster-quarkus/pull/64

Can we merge?

**Comment by danielpetisme** [comment]
Fixed
