### ISSUE TITLE
Add jhipster-quarkus and generated sample projects to JHipster sonar

### ISSUE THREAD

**Issue by joewhite101** [jhipster/jhipster-quarkus#68]
**Is your feature request related to a problem? Please describe.**
It would be great to see the jhipster-quarkus and jhipster quarkus example project available on the JHipster sonar.

**Describe the solution you'd like**
Projects show up here:
https://sonarcloud.io/organizations/jhipster/projects

**Describe alternatives you've considered**
N/A

**Additional context**
May require a Sonar admin

**Comment by joewhite101** [comment]
@jhipster/developers Can somebody add these two projects to the JHipster sonar or give me the temporary ability to add them? I don't think I have the ability to do it right now.

https://github.com/jhipster/jhipster-quarkus
https://github.com/jhipster/jhipster-sample-app-quarkus

I ran the analysis on the generator on a fork and it was clean (link below). Working on adding the ci for the sample app but I think it needs to be fully regenerated with an updated release.

https://sonarcloud.io/organizations/joewhite101/projects

Thanks!

**Comment by pascalgrimaud** [comment]
I'll take care of this @joewhite101

**Comment by pascalgrimaud** [comment]
I  added the 2 projects at https://sonarcloud.io/organizations/jhipster/projects

For https://github.com/jhipster/jhipster-quarkus, the Sonar Analysis should be done automatically:
- https://sonarcloud.io/dashboard?id=jhipster_jhipster-quarkus

For https://github.com/jhipster/jhipster-sample-app-quarkus, I added a secret (SONAR_TOKEN) to the repository. A build with GitHub actions need to be done for pushing the Sonar Analysis, maybe something similar to https://github.com/jhipster/jhipster-control-center/blob/master/.github/workflows/github-ci.yml#L43-L50
Here the information, which needs to be used:
- sonar.host.url : https://sonarcloud.io
- sonar.projectKey : jhipster_jhipster-sample-app-quarkus
- sonar.organization: jhipster
- sonar.login: `$SONAR_TOKEN` (which has been set in the secret of the repository)

Don't hesitate to ping me if something doesn't work and I'll check the settings again :-)

**Comment by joewhite101** [comment]
Thanks @pascalgrimaud I'll close this one and open a new ticket for the CI on the sample project. I played with it this weekend but the build isn't working. Looks like the project needs to be regenerated.
