### ISSUE TITLE
Support Gradle as a build tool in the Quarkus blueprint

### ISSUE THREAD

**Issue by joewhite101** [jhipster/jhipster-quarkus#79]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by avdev4j** [comment]
It seems that gradle option is already here, could we have to do something more?

**Comment by joewhite101** [comment]
I don't think it is fully supported. Does it work?  I haven't had a chance to test it yet.

**Comment by inngvar** [comment]
let me know if something not working

**Comment by joewhite101** [comment]
If we've done the work and you guys have tested we can close. I was going based on a roadmap document and maybe it was a bit out of date.

**Comment by avdev4j** [comment]
I've just tested now (by adding the health check dependency) and I think it's done. But I'm not an expert of Gradle. 
I was able to run the application, reach out the frontend and connect to the backend.

**Comment by avdev4j** [comment]
Same here, I close this ticket since it seems that current implementation is working well.
