### ISSUE TITLE
Active Record pattern

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-quarkus#8]
Quarkus Hibernate Panache proposes the active record and repository patterns.
Currently only the repository pattern is implemented (because it was the easiest one to duplicate from a JHipster Spring).

The objective is to proposes a new prompt to the user to choose between the 2 patterns and update the templates to generate active records.

**Comment by antmordel** [comment]
I think I can take this one! :)

**Comment by danielpetisme** [comment]
Fixed via #42
