### ISSUE TITLE
Support embedded h2

### ISSUE THREAD

**Issue by joewhite101** [jhipster/jhipster-quarkus#81]
**Is your feature request related to a problem? Please describe.**
Allow users of the blueprint to select embedded h2 as a database

Example and instructions
https://quarkus.io/guides/datasource

**Describe the solution you'd like**
Embedded h2 database works as a datasource and is correctly configured in your quarkus app after running the blueprint

**Describe alternatives you've considered**
N/A

**Additional context**
https://quarkus.io/guides/datasource

**Comment by avdev4j** [comment]
I've tested and H2 already works as expected as dev database. As we don't use h2 for production mode, it seems we have 
nothing to do more.
@joewhite101 WDYT about closing this ticket?

**Comment by joewhite101** [comment]
both in memory and on disk are supported? For some reason I thought we were missing one of them. Need to double check that we're using the appropriate type based on user selection and then we can close.

**Comment by avdev4j** [comment]
Oh yea, I did not check in details. I can do that this afternoon.

**Comment by avdev4j** [comment]
I've checked that both disk and memory work as expected. I don't saw anything wrong. @joewhite101 I let you to check on your side and close it if we consider that's the current state is ok.

**Comment by avdev4j** [comment]
I think this feature work as excepted. I close this ticket for the moment, we could new ones if needed.
